const SET_SEARCH = 'SET_SEARCH'
const SET_LOADING = 'SET_LOADING'
const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_PRODUCT = 'SET_PRODUCT'
const SET_PAGE = 'SET_PAGE'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_PER_PAGE = 'SET_PER_PAGE'
const SET_HAS_REQUEST = 'SET_HAS_REQUEST'
const SET_PRODUCT_TO_CART = 'SET_PRODUCT_TO_CART'
const SET_PRODUCT_COUNT = 'SET_PRODUCT_COUNT'
const SET_UPDATED_PRODUCT_TO_CART = 'SET_UPDATED_PRODUCT_TO_CART'

export {
  SET_SEARCH,
  SET_CURRENT_PAGE,
  SET_LOADING,
  SET_PAGE,
  SET_PER_PAGE,
  SET_PRODUCTS,
  SET_PRODUCT,
  SET_HAS_REQUEST,
  SET_PRODUCT_TO_CART,
  SET_PRODUCT_COUNT,
  SET_UPDATED_PRODUCT_TO_CART
}


